top:
  inept:
    datasource:
      ddl-auto: validate
      url: jdbc:postgresql://localhost:5432/testdb
      username: test
      password: test
    server:
      port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update