spring:
  application:
    name: suiji-server
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${top.inept.datasource.host}:${top.inept.datasource.port}/${top.inept.datasource.database}
    username: ${top.inept.datasource.username}
    password: ${top.inept.datasource.password}

  jpa:
    hibernate:
      ddl-auto: ${top.inept.datasource.ddl-auto}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

  messages:
    basename: i18n/messages,i18n/validation,i18n/openapi
    encoding: UTF-8
    fallback-to-system-locale: false

server:
  port: ${top.inept.server.port}

