top:
  inept:
    datasource:
      ddl-auto: validate
      url: jdbc:postgresql://localhost:5432/test
      username: test
      password: test

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop